#!/bin/bash

# Optional fields
# script name: add-htpasswd-identity-provider
# script description: Install a sample htpasswd file with admin, user and guest users

# Mandatory function
# start main - do not remove this line and do not change the function name
main() {
  _oc="${3} --kubeconfig=${2}/auth/kubeconfig"

  # passwords are generated based on the username
  # function claveOCP() { echo $1$1$1 | base64 -w8 | head -n 1; }
  htpasswd -bc htpasswd admin YWRtaW5h
  htpasswd -b htpasswd user dXNlcnVz
  htpasswd -b htpasswd guest Z3Vlc3Rn

  ${_oc} delete secret htpasswd-secret -n openshift-config || true
  ${_oc} create secret generic htpasswd-secret --from-file htpasswd -n openshift-config
  rm -fr htpasswd

  echo "
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: htpasswd
    challenge: true
    login: true
    mappingMethod: claim
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpasswd-secret
" | ${_oc} apply -f -
  ${_oc} adm policy add-cluster-role-to-user cluster-admin admin
}
# end main - do not remove this line

# Optionally, keep this if you want to run your script manually or for testing.
main $@
