#!/bin/bash

# start main - do not remove this line and do not change the function name
main() {
  echo "Bye world!"
}
# end main - do not remove this line

# Keep this if you want to run your script manually or for testing.
if [[ -z $WRAPPER ]]; then
  main
fi

