#!/bin/bash

# Optional fields
# script name: delete-kubeadmin-user
# script description: Removes the kubeadmin secret

# Mandatory function
# start main - do not remove this line and do not change the function name
main() {
  oc delete secret kubeadmin -n kube-system \
      && success "Secret kubeadmin successfully deleted." \
      || err "Error deleting kubeadmin secret. It probably doesn't exists anymore. Skipping."
}
# end main - do not remove this line

# Optionally, keep this if you want to run your script manually or for testing.
main $@
