#!/bin/bash

# Optional fields
# script name: deploy-rhsso
# script description: Installs RHSSO operator and deploys an instance

# Mandatory function
# start main - do not remove this line and do not change the function name
main() {
  # default values
  namespace=rhsso
  version=7.4.2
  channel=alpha

  # parse parameters from ${1}
  # NOTE: I tried to use bash substring extraction but failed when merging the script
  IFS=',' read -r -a params <<< "${1}"
  for index in "${!params[@]}"; do
    declare $( echo ${params[index]} | cut -d = -f 1 )=$( echo ${params[index]} | cut -d = -f 2 )
  done

  # Create the namespace to deploy the operator
  _oc create namespace ${namespace} \
      && success "Namespace rhsso created successfully." \
      || err "Error creating the Namespace. It probably already exists. Continuing..."

  # Create the operatorgroup
  cat <<EOF | _oc apply -f - \
                  && success "OperatorGroup created succesfully." \
                  || die "Error creating the OperatorGroup."
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhsso-operator
  namespace: ${namespace}
spec:
  targetNamespaces:
  - ${namespace}
EOF

  # Create the subscription
  cat <<EOF | _oc apply -f - \
                  && success "Subscription created succesfully." \
                  || die "Error creating the Subscription."
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhsso-operator
  namespace: ${namespace}
spec:
    channel: ${channel}
    installPlanApproval: Automatic
    name: rhsso-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: rhsso-operator.${version}
EOF

  # Wait for a few seconds
  verbose "Pausing fo 5 seconds..."
  sleep 5

  # Create the Keycloak instance
  cat <<EOF | _oc apply -f - \
                  && success "Keycloak instance created successfully." \
                  || die "Error creating Keycloak instance."
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: sso
  namespace: ${namespace}
  labels:
    app: sso
spec:
  externalAccess:
    enabled: true
  instances: 1
EOF

  # Create the realm
  cat <<EOF | _oc apply -f - \
                  && success "KeycloakRealm instance created successfully." \
                  || die "Error creating KeycloakRealm."
apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: realm
  namespace: ${namespace}
  labels:
    app: sso
spec:
  realm:
    id: realm
    realm: realm
    enabled: True
    displayName: "Realm"
  instanceSelector:
    matchLabels:
      app: sso
EOF
}
# end main - do not remove this line

# Optionally, keep this if you want to run your script manually or for testing.
main $@
